### ISSUE TITLE
Help to better understand the limitations of this library

### ISSUE THREAD

**Issue by nbaleli-w** [noppa/ng-hot-reload#18]
I'm experimenting with this lib, got it working and it's truly amazing work !

One thing though, can you please share from your experience, what exactly not to do to avoid a full page refresh ?

this code for example, works. when either editing the controller or the template:

```typescript
import * as angular from "angular";
import "./test.scss";

const template = require("./test.html");

class TestComponentController {
    test: boolean;
    constructor() {
        this.test = true;
    }

    $onInit(): void {}
}

export const TestComponent: any = {
    selector: "appTest",
    controller: TestComponentController,
    template
};

export const TestPageModule = angular
    .module("app.pages.test", [])
    .config($stateProvider => {
        "ngInject";
        $stateProvider.state("test", {
            url: "/marketplace",
            template: "<test></test>"
        });
    })
    .component(TestComponent.selector, TestComponent);

```

**Comment by noppa** [comment]
Thanks. The library is focused on making UI development easy, as that's where I think hot reloading is most valuable.

Services and factories are not hot reloaded at all and modifications to them always cause a hot reload. Supporting them would've been more difficult for various reasons; services are often very stateful, they are considered singletons so there's no way to define cleanup phase to run on hot swap and tracking all the directives and controllers that need to be reloaded when a service changes whould've meant more work. It probably wouldn't be impossible to support them, but I didn't think it was worth the effort. I recommend developing services and factories separately with more TDD/unit testing and hot reloading just for the view stuff (directives and components, mainly).

UI router states don't get special hot reload handing. The library used to have special UI-Router support in an earlier version, but I removed it as unnecessary (and buggy) feature when UI-Router's [component routes](https://ui-router.github.io/guide/ng1/route-to-component) were introduced and started to get popular. Components are hot reloaded, so theres' no need for special UI-Router route handling. So I recommend refactoring UI-Router states to the component style:
```javascript
// Before 
    .config($stateProvider => {
        "ngInject";
        $stateProvider.state("test", {
            url: "/marketplace",
            template: "<test></test>"
        });
    })

// After 
    .config($stateProvider => {
        "ngInject";
        $stateProvider.state("test", {
            url: "/marketplace",
            component: 'appMarketplace', // or whatever you name the component
        });
    })
```
For more information about component routes, see [Migrate to components](https://ui-router.github.io/guide/ng1/route-to-component#migrate-to-components) in UI-Router's docs.

Use one file per one component/directive. Having multiple components in one file will cause unnecessary reloads in the other component when you only needed to edit the other. Separating components into their own files is generally a good practice anyway. Having services, factories, configs etc. defined in the same file as a directive definition will cause a hard reload, because services are not hot reloaded as mentioned before.

Adding/removing injected dependencies to a directive/component will cause a hard reload, but well that's not something you can really avoid - when you need to add a new injected dependency you just add it, it's probably not such a common case anyway that one would need to worry about it.

The library tries to preserve state of the component when a hot reload happens. This can be really useful if you have some state like
```javascript
this.modalOpen = false
```
If you open the modal in that component (`this.modalOpen = true)` and then modify the file, we can 
keep `this.modalOpen = true` after the hot reload. A few general practices can help with this. First, initialize/declare the properties that you are going to have in the controller or scope in constructor (as you have done in your example).
```javascript
// Good
class MyController {
  modalOpen = false
  openModal() {
    this.modalOpen = true
  }
}
// Bad
class MyController {
  openModal() {
    // modalOpen won't be preserved on hot reload because
    // the property wasn't there on initialization phase!
    this.modalOpen = true
  }
}
```
If you are using TypeScript, it tends to make you write your code this way anyway.  
Asynchronous state can also be a bit tricky if you want that to be hot reloaded
```javascript
class MyController {
  users = []
  constructor(userService) { this.userService = userService }
  $onInit() {
    this.userService.fetchUsers().then(users => {
      // ng-hot-reload might have preserved the earlier users array,
      // but this overwrites that
      this.users = users
    })
  }
  addUser(name) { this.users.push({name})
}
```
This might not be a problem because usually async data comes from some datastore that is kept in sync with the `this.users` property anyway, so the users list you get after fetch is up to date. However if that's not the case, for example if your view doesn't save the data automatically and you want to edit the component without saving the changes you make to the data, you can write checks like
```javascript
  const defaultUsersList = []
  this.users = defaultUsersList
  this.fetchUsers().then(users => {
    // If ng-hot-reload has swapped this.users list, this will be false
    const usersListIsUnchanged = this.users === defaultUsersList
    if (usersListIsUnchanged) {
      this.users = users
    }
  })
```
Note that wheter that works correctly is largely depends on your controller and data. In worst case scenario condition like that could even cause production bugs, so you need to use your own judgement to determine if that approach works for you.

Finally, the preserved state properties will need to be copyable. Uncopyable values include, for example, error objects, functions, DOM nodes, WeakMaps, window, $rootScope and any injected values, like services.
```javascript
  addUser(firstName, lastName) {
    const userService = this.userService
    this.users.push({
      firstName, lastName,
      // This function will make it impossible to preserve users list on state reload
      save() { return userService.saveUser(this)
     })
  }
```
Class instances are preserved and can have methods in the prototype, so you might be able to get around the limitation above by having a `User` class. Once again it depends on your project if that's applicable.

On the opposite case, it's also possible that state is preserved and _that_ causes issues, due to reference equality being lost in the copying process, for example.

```javascript
this.countryOptions = [{ countryCode: 'US' }, { countryCode: 'FI' }]
this.selectedCountry = this.countryOptions[0]
// somewhere else...
doSomething() {
  // This condition will always be false after a state reload!
  // Both selectedCountry and countryOptions have been cloned so === doesn't work anymore.
  if (this.selectedCountry === this.countryOptions[0]) {
    ..
  }
}
```
If state reloading causes issues like that, you can turn it off in the [library options](https://github.com/noppa/ng-hot-reload#client-options) with `preserveState: false`, or (once again if your application code so permits) you can avoid some of the issues with e.g. using `this.selectedCountry.countryCode === this.countryOptions[0].countryCode`.

Last but not least there are a few [issues](https://github.com/noppa/ng-hot-reload/issues) that have been open here for quite a while, related to Angular 2+ and lazy loading. I haven't had much time to look into those, so you I guess you'll have smoother sailing if you try to avoid the use cases that are described in those issues.

I hope you have pleasant development experience with AngularJS and the library.

**Comment by nbaleli-w** [comment]
I appreciate the thorough answer, thank you !
Ill keep experimenting along with the info you just gave me.

BTW this should probably go in the readme ?

**Comment by noppa** [comment]
Yeah I'll try find some time to add this stuff in there. We can keep this issue open until it's done.
