### ISSUE TITLE
Error in the build

### ISSUE THREAD

**Issue by alessandro308** [noppa/ng-hot-reload#31]
I just followed the example but I find that error:

```
ERROR in ./src/index.js 16:0
Module parse failed: 'import' and 'export' may only appear at the top level (16:0)
File was processed with these loaders:
 * ./node_modules/angularjs-template-loader/index.js
 * ./node_modules/ng-hot-reload-loader/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     (function() {/* ng-hot-reload-loader end*/
|
> import 'js/main.module';
| import 'resources/my/js/unsupportedBrowserCheck.js';
|
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.js main[2]
```

Any idea? It seems that the loader wrap the code as it has to do but then Webpack is not able to build it anymore

**Comment by noppa** [comment]
Unfortunately, the way this plugin works requires that ES6 imports have been compiled to CommonJS requires first. 
 
If you are using Babel and preset-env, add `"moduels": "commonjs"`, like [in this example](https://github.com/noppa/ng-hot-reload/blob/6494dd7f0361933151d95802509d08cfe5c4125d/packages/demo/webpack-example/.babelrc#L6).

If you are using TypeScript, add `"module": "commonjs"` to tsconfig, like [in this example](https://github.com/noppa/ng-hot-reload/blob/6494dd7f0361933151d95802509d08cfe5c4125d/packages/demo/webpack-typescript-example/tsconfig.json#L6).

Note that when you do this, Webpack's tree shaking doesn't work, which may make your bundles bigger.
You might want to configure those tools so that the CommonJS compilation is used only when debugging with hot reloading and not in production.

With Babel, that can be achieved with `"env"` option in babelrc ([docs](https://babeljs.io/docs/en/options#env), [example in StackOverflow](https://stackoverflow.com/a/35462890/6184698)).  

With TypeScript, you can pass something like
```javascript
options: {
  compilerOptions: {
    module: process.env.NODE_ENV === 'production' ? 'ES6' : 'commonjs',
  }
}
```
using ts-loader ([docs](https://github.com/TypeStrong/ts-loader#compileroptions))

**Comment by alessandro308** [comment]
Thanks a lot! It fixes the error even if now instead of `module: 'commonjs'` a plugin is required:  https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs

**Comment by noppa** [comment]
Closing as this seems to be solved
